### ISSUE TITLE
Can replace nginx ?(in future)

### ISSUE THREAD

**Issue by elycheikhsmail** [Octo8080/regali#1]
can regali replace nginx or apach proxy ?

**Comment by Octo8080X** [comment]
In my opinion, the purpose of A is to use it in a development environment, not a production environment.

However, if you continue to use it and get results, I would like you to take advantage of it.

**Comment by elycheikhsmail** [comment]
> In my opinion, the purpose of A is to use it in a development environment, not a production environment.
> 
> However, if you continue to use it and get results, I would like you to take advantage of it.

thank you
